### ISSUE TITLE
curl_easy_perform() failed: Timeout was reached

### ISSUE THREAD

**Issue by agatheLG123** [aviks/SMTPClient.jl#47]
Hi, 
This is an issue type "help wanted" but I din't know how to add a label.
I want to send an email from julia code however I am a newbie in email sending so I am having a hard time understanding how to use your package. 
I added the verbose=true in `opt = SendOptions(verbose=true)` I tried adding my email and password with or without ssl true. I instantiated from, rcpt, body. However my errors might come from the url which I have no clue how to fill... I am testing this code with my work email (....@centralesupelec.fr) so I try to mimic what was in your example and chose for my url "_smtps://smtp.centralesupelec.fr:465_", I also tried with "_smtp://smtp.centralesupelec.fr:465_" but in both cases I had the messages : _Trying 138.195.33.53:465..._  but then  _connect to ... port 465 failed: Connection refused_. I am executing this code from a docker container so I then tried for the url to write` url="smtp://docker_name:docker_port"` and in this case the connection work, I have a message : _Connected to docker_name port docker_port (#0)_. However then it waits a long time and then I have the messages :  _server response timeout_, _closing connection 0 with this error_:
_ERROR: curl_easy_perform() failed: Timeout was reached
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at /home/genie/.julia/packages/SMTPClient/psZKQ/src/utils.jl:8 [inlined]
 [3] connect(::SMTPClient.ConnContext) at /home/genie/.julia/packages/SMTPClient/psZKQ/src/types.jl:115
 [4] do_send(::String, ::Array{String,1}, ::String, ::SendOptions, ::SMTPClient.ReadData{Base.GenericIOBuffer{Array{UInt8,1}}}) at /home/genie/.julia/packages/SMTPClient/psZKQ/src/mail.jl:14
 [5] send(::String, ::Array{String,1}, ::String, ::Base.GenericIOBuffer{Array{UInt8,1}}, ::SendOptions) at /home/genie/.julia/packages/SMTPClient/psZKQ/src/mail.jl:2
 [6] top-level scope at REPL[23]:1_

If you have any idea of what I am doing wrong, your help would be much appreciated.

**Comment by aviks** [comment]
Hi @agatheLG123 , as you guessed your problem is connecting to the smtp server for your organisation. Unfortunately, I won't be able to help with that, since I cannot know how your smtp server is set up. you'll have to talk to the people who maintain your server, and ask them what the correct host/port combination is for connecting. I'd guess that the port you are trying is wrong, but I wouldn't know what the correct port should be. Alternatively, there could be a firewall in front of that server that prevents you from connecting.
